<a href="https://colab.research.google.com/github/patilyogita7/Artificial_Intelligence_Lab_SE_A_45/blob/master/Practical_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Student_Performance.csv to Student_Performance.csv

In [4]:
df=pd.read_csv('Student_Performance.csv')
df.tail()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [7]:


print("\nStudy hours statistics grouped by gender:")
std_hrs_by_gender = df.groupby('gender')['study_hours']
print(std_hrs_by_gender.agg(['count', 'sum', 'min', 'max', 'mean', 'median', 'std', 'var']))

Study hours statistics grouped by gender:
        count      sum  min  max      mean  median       std       var
gender
female   8290  35414.3  0.5  8.0  4.271930     4.3  2.168079  4.700567
male     8247  35115.9  0.5  8.0  4.258021     4.3  2.164374  4.684517
other    8463  35800.4  0.5  8.0  4.230226     4.3  2.170146  4.709535

In [16]:
df['math_score'].describe()

count    25000.000000
mean        63.785944
std         20.875262
min          0.000000
25%         48.300000
50%         64.100000
75%         80.000000
max        100.000000
Name: math_score, dtype: float64

In [17]:
df[df['science_score'] > 80]

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
10,11,17,female,private,graduate,6.1,90.5,yes,15-30 min,no,notes,75.4,82.7,70.8,77.5,c
12,13,18,female,private,high school,6.8,58.2,yes,>60 min,no,mixed,75.1,80.5,56.2,73.6,c
23,24,19,female,public,phd,7.8,72.8,yes,15-30 min,yes,notes,100.0,100.0,100.0,94.6,b
25,26,17,male,private,diploma,8.0,77.4,yes,>60 min,no,coaching,100.0,87.7,69.3,92.5,b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24982,7420,18,male,private,post graduate,6.1,86.8,yes,30-60 min,yes,mixed,84.3,95.1,100.0,90.4,b
24988,3558,16,male,private,phd,5.8,53.4,yes,>60 min,no,coaching,91.5,85.6,75.3,74.1,c
24990,12602,15,male,public,diploma,5.8,86.6,yes,<15 min,no,online videos,93.0,100.0,100.0,86.3,b
24991,3251,16,female,private,no formal,4.6,62.7,yes,30-60 min,yes,online videos,50.0,82.7,55.9,59.1,d
24992,8062,17,female,private,post graduate,5.4,96.9,yes,<15 min,yes,notes,79.2,94.0,77.9,79.5,c